# FRONT OFFICE
homepage:
  path: /
  defaults: { _controller: 'Controller\PageController::goHome' }

revues :
  path: /revues
  defaults: { _controller: 'Controller\RevuesController::listRevues' }

revuesregion :
  path: /revues?region={region}
  defaults: { _controller: 'Controller\RevuesController::regionAction' }

detailrevues :
  path: /revue?id={id}
  defaults: { _controller: 'Controller\RevuesController::detailRevue' }

actus :
  path: /actus
  defaults: { _controller: 'Controller\ActusController::afficheActusFront' }

detailactu :
  path: /actu?id={id}
  defaults: { _controller: 'Controller\ActusController::afficheUneActu' }

commander :
  path: /commander
  defaults: { _controller: 'Controller\CommandeController::afficheCommande' }

commander un seul :
  path: /commander?id={id}&step=1
  defaults: { _controller: 'Controller\CommandeController::afficheCommande' }

commander etape 2 :
  path: /commander?id={id}&step=2
  defaults: { _controller: 'Controller\CommandeController::afficheCommande' }

commander etape 3 :
  path: /commander?id={id}&step=3
  defaults: { _controller: 'Controller\CommandeController::afficheCommande' }

commander confirmation:
  path: /commanderconfirmation
  defaults: { _controller: 'Controller\CommandeController::confirmCommande' }

quisommesnous :
  path: /quisommesnous
  defaults: { _controller: 'Controller\PageController::goQui' }

mentionslegales :
  path: /mentions
  defaults: { _controller: 'Controller\PageController::goMentions' }

contact :
  path: /contact
  defaults: { _controller: 'Controller\PageController::goContact' }

abonnement :
  path: /abonnement
  defaults: { _controller: 'Controller\PageController::goAbonnement' }

Offre :
  path: /offre
  defaults: { _controller: 'Controller\PageController::goOffre' }


# BACK OFFICE

admin :
  path: /admin
  defaults: { _controller: 'Controller\RevuesController::listAction' }

# Gestion des revues
admin-add-revues :
  path: /admin/addrevues
  defaults: { _controller: 'Controller\RevuesController::addAction' }

admin-modif-revues :
  path: /admin/modifrevues?id={id}
  defaults: { _controller: 'Controller\RevuesController::updateAction' }

admin-delete-revues :
  path: /admin/deleterevues?id={id}
  defaults: { _controller: 'Controller\RevuesController::deleteAction' }


# Gestion des actualités
admin-actus :
  path: /admin/actus
  defaults: { _controller: 'Controller\ActusController::afficheActus' }

admin-add-actus :
  path: /admin/addactus
  defaults: { _controller: 'Controller\ActusController::addAction' }

admin-modif-actus :
  path: /admin/modifactus?id={id}
  defaults: { _controller: 'Controller\ActusController::updateAction' }

admin-delete-actus :
  path: /admin/deleteactus?id={id}
  defaults: { _controller: 'Controller\ActusController::deleteAction' }

# Gestion des partenaires
admin-partenaires :
  path: /admin/partenaires
  defaults: { _controller: 'Controller\PartenairesController::affichePartenaires' }

admin-add-partenaires :
  path: /admin/addpartenaires
  defaults: { _controller: 'Controller\PartenairesController::addPartenaire' }

admin-modif-partenaires :
  path: /admin/modifpartenaire?id={id}
  defaults: { _controller: 'Controller\PartenairesController::updatePartenaire' }

admin-delete-partenaires :
  path: /admin/deletepartenaire?id={id}
  defaults: { _controller: 'Controller\PartenairesController::deletePartenaire' }