homepage:
  path: /
  defaults: { _controller: 'Controller\PageController::goHome' }

actus :
  path: /actus
  defaults: { _controller: 'Controller\ActusController::afficheActus' }

actu :
  path: /actu?id={id}
  defaults: { _controller: 'Controller\ActusController::afficheActus' }

commander :
  path: /commander
  defaults: { _controller: 'Controller\CommandeController::afficheCommande' }

admin :
  path: /admin
  defaults: { _controller: 'Controller\RevuesController::listAction' }

admin-add-revues :
  path: /admin/addrevues
  defaults: { _controller: 'Controller\RevuesController::addAction' }

admin-modif-revues :
  path: /admin/modifrevues?id={id}
  defaults: { _controller: 'Controller\RevuesController::updateAction' }

admin-delete-revues :
  path: /admin/deleterevues?id={id}
  defaults: { _controller: 'Controller\RevuesController::deleteAction' }

admin-partenaires :
  path: /admin/partenaires
  defaults: { _controller: 'Controller\PageController::tempPartenaires' }

admin-actus :
  path: /admin/actus
  defaults: { _controller: 'Controller\PageController::tempActus' }

